In [1]:
import numpy as np

In [16]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
c = b.T
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
'''
    共n个数字，每隔k个人报一次数字，是怎么报数的？（这里恰好n可以被k整除）
'''
n = 56
k =7
s1 = np.arange(1,n+1).reshape(-1,k).T
s1
s2 = s1.flatten()
s2

array([ 1,  8, 15, 22, 29, 36, 43, 50,  2,  9, 16, 23, 30, 37, 44, 51,  3,
       10, 17, 24, 31, 38, 45, 52,  4, 11, 18, 25, 32, 39, 46, 53,  5, 12,
       19, 26, 33, 40, 47, 54,  6, 13, 20, 27, 34, 41, 48, 55,  7, 14, 21,
       28, 35, 42, 49, 56])