In [2]:
import tensorflow as tf

# 今天就解决一个问题：图片转数组

## 1.构造文件名队列
## 2.读取与解码
## 3.统一数据格式
## 4.放入批处理队列
## 5.启动线程

In [5]:
import os

In [28]:
'''
    返回带路径+文件名的列表
'''
def picture_read():
    path = '../../../MyDataSets/pic/mypic'
    filenames = os.listdir(path)
    #拼接
    fullname = [os.path.join(path + "/",filename) for filename in filenames]
    #print("fullname\n",fullname)
    return fullname

ERROR! Session/line number was not unique in database. History logging moved to new session 38


In [29]:
'''
    图片转数组
'''
def picture_deal():
    file_list = picture_read();
    
    #1.构造文件名队列
    file_queue = tf.train.string_input_producer(file_list)
    
    #2.读取
    reader = tf.WholeFileReader()
    key,value = reader.read(file_queue)
    
    #3.解码
    image = tf.image.decode_jpeg(value)
    
    #4.统一数据格式
    image_new = tf.image.resize_images(image,size=[200,200])
    #print("image\n",image)
    image_new.set_shape(shape=[200,200,3])
    
    #5.批处理
    image_batch = tf.train.batch([image_new],batch_size=2,num_threads=1,capacity=100)
    print("image_batch:\n",image_batch)
    
    with tf.Session() as sess:        
        #线程管理员
        coord = tf.train.Coordinator()
        #开启线程
        tasks = tf.train.start_queue_runners(sess=sess,coord=coord)
        
        #执行图
        value,image = sess.run([value,image])
        print("image:\n",image)
        
        #结束并回收线程资源
        coord.request_stop()
        coord.join(tasks)

In [ ]:
picture_deal()

Exception in callback BaseAsyncIOLoop._handle_events(1144, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(1144, 1)>
Traceback (most recent call last):
  File "c:\users\fangxiang\anaconda3\Lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "d:\python环境\learn\lib\site-packages\tornado\platform\asyncio.py", line 138, in _handle_events
    handler_func(fileobj, events)
  File "d:\python环境\learn\lib\site-packages\zmq\eventloop\zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "d:\python环境\learn\lib\site-packages\zmq\eventloop\zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "d:\python环境\learn\lib\site-packages\zmq\eventloop\zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "d:\python环境\learn\lib\site-packages\ipykernel\iostream.py", line 120, in _handle_event
    event_f()
  File "d:\python环境\learn\lib\site-packages\ipykernel\iostream.py", line 382, in _flush
    parent

image:
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 86  92 104]
  [ 81  87  99]
  [ 85  91 103]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 86  92 104]
  [ 84  90 102]
  [ 84  90 102]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 85  91 103]
  [ 86  92 104]
  [ 84  90 102]]

 ...

 [[140 147 153]
  [139 146 152]
  [135 142 148]
  ...
  [110 121 125]
  [113 124 128]
  [112 123 127]]

 [[141 148 154]
  [142 149 155]
  [142 149 155]
  ...
  [110 121 125]
  [111 122 126]
  [110 121 125]]

 [[142 149 155]
  [142 149 155]
  [142 149 155]
  ...
  [110 121 125]
  [108 119 123]
  [109 120 124]]]
